# ANNOTATION config
PROTEINS_FILE: test/proteins.fasta
OUTPUT_DIR: test/ANNOTATION_OUTPUT

CLUSTERING:
  IDENTITY: 0.5
  COVERAGE: 0.8
  EVAL: 0.001
  SENSITIVITY: 8.5

HHSUITE:
  PHROGS: '/home/MCB/jkoszucki/storage/dbmgg/databases/hhsuite/phrogs_hhsuite_db/phrogs'
  PFAM: '/home/MCB/jkoszucki/storage/dbmgg/databases/hhsuite/Pfam-hh_35_0/pfam'
  ECOD: '/home/MCB/jkoszucki/storage/dbmgg/databases/hhsuite/ECOD_F70_db/ECOD_F70_20220113'
  ALANDB: '/home/MCB/jkoszucki/storage/dbmgg/databases/hhsuite/AlanDavidson_hhsuite_db/all_proteins'

METADATA:
  PHROGS_ANNOT: 'tables/phrog_annot_v4.tsv'
  MGG_PHROGS_ANNOT: 'tables/v3_phrogs-table-rafal-3_12.csv'
  ALAN_ANNOT: 'tables/alan_annot.tsv'
